//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLibrary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class book
    {
        public int IdBook { get; set; }

		[Required]
		[Display(Name = "Category")]
		public int IdCategory { get; set; }

		[Required]
		[StringLength(50)]
		[Display(Name = "Book Name")]
		public string NameBook { get; set; }

		[StringLength(150)]
		[Display(Name = "Book Description")]
		public string DescriptionBook { get; set; }

		[Required]
		[DataType(DataType.Date)]
		[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
		[Display(Name = "Publication Date")]
		public System.DateTime PublicationDateBook { get; set; }
        public int IsActive { get; set; }
    
        public virtual category category { get; set; }
    }
}
